name: Deploy

on:
  workflow_run:
    workflows: ["Deploy to AWS ECR"]
    types:
      - completed
    branches:
      - main
      - develop
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main, develop]
  push:
    branches: [main, develop]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials for Dynamic Region
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_ACCESS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::576661951794:role/GitHubActions-ServerlessDeploy
      - name: Deploy to EFS
        env:
          DEPLOY_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'staging' }}
        run: |
          echo "Triggering call to deploy to $DEPLOY_ENVIRONMENT environment"
          FUNCTION_NAME="edna-explorer-$DEPLOY_ENVIRONMENT-reports"
          PAYLOAD='{"reportType": "update", "reportId": "'"$(date +%Y%m%d%H%M%S)"'"}'
          aws lambda invoke --function-name $FUNCTION_NAME --payload "$PAYLOAD" response.json
