name: Build & Test

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  deploy:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    env:
      SSH_ADDRESS: ${{ github.ref == 'refs/heads/main' && secrets.SSH_ADDRESS_PROD || secrets.SSH_ADDRESS }}
      SSH_USER: ${{ github.ref == 'refs/heads/main' && secrets.SSH_USER_PROD || secrets.SSH_USER }}
      SSH_PASSWORD: ${{ github.ref == 'refs/heads/main' && secrets.SSH_PASSWORD_PROD || secrets.SSH_PASSWORD }}
      SSH_KEY: ${{ github.ref == 'refs/heads/main' && secrets.SSH_KEY_PROD || secrets.SSH_KEY }}
      DEPLOY_ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'PRODUCTION' || 'STAGING' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to EFS
        run: |
          echo "Triggering call to deploy to $DEPLOY_ENVIRONMENT environment"
          curl -X POST -H "Content-Type: application/json" -d '{"reportType": "update", "reportId": "'"$(date +%Y%m%d%H%M%S)"'"}' https://o467wx4u0b.execute-api.us-west-1.amazonaws.com/default/edna-explorer-staging-reports
